{{- if or .Values.database.postgresql.host .Values.database.mysql.host .Values.database.redis.host }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "microservice.fullname" . }}-db-secret
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.database.postgresql.username }}
  postgresql-username: {{ .Values.database.postgresql.username | b64enc }}
  {{- end }}
  {{- if .Values.database.postgresql.password }}
  postgresql-password: {{ .Values.database.postgresql.password | b64enc }}
  {{- end }}
  {{- if .Values.database.mysql.username }}
  mysql-username: {{ .Values.database.mysql.username | b64enc }}
  {{- end }}
  {{- if .Values.database.mysql.password }}
  mysql-password: {{ .Values.database.mysql.password | b64enc }}
  {{- end }}
  {{- if .Values.database.redis.password }}
  redis-password: {{ .Values.database.redis.password | b64enc }}
  {{- end }}
{{- end }}